//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerticalculoWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvencasEntity
    {
        public int Id { get; set; }
        public int ClienteId { get; set; }
        public int ContabilistaId { get; set; }
        public string Descricao { get; set; }
        public double Valor { get; set; }
        public System.DateTime DataAvenca { get; set; }
        public string EstadoPagamento { get; set; }
        public Nullable<System.DateTime> DataPagamento { get; set; }
        public bool AvisoPagamento { get; set; }
    
        public virtual UserProfiles Cliente { get; set; }
        public virtual UserProfiles Contabilista { get; set; }
    }
}
