//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerticalculoWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfiles
    {
        public UserProfiles()
        {
            this.AvencasEntity = new HashSet<AvencasEntity>();
            this.AvencasEntity1 = new HashSet<AvencasEntity>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<AvencasEntity> AvencasEntity { get; set; }
        public virtual ICollection<AvencasEntity> AvencasEntity1 { get; set; }
    }
}
