// <auto-generated />
namespace VerticalculoWebsite.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class NoticiasProfileChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NoticiasProfileChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201507211434415_NoticiasProfileChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
